### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [santhoshtr/wikivue#33]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by santhoshtr** [comment]
It is not active. But it is not dead either. As you can read from documentaiton, this was an exploration of an idea. A working version is available(https://wikipedia.thottingal.in/). 

I welcome contributions that are substantial and important. Not README updates or minor cosmetic changes.

**Comment by ghost** [comment]
Hi santhoshtr.

> It is not active. But it is not dead either. As you can read from documentaiton, this was an exploration of an idea. A working version is available(https://wikipedia.thottingal.in/).
> I welcome contributions that are substantial and important. Not README updates or minor cosmetic changes.

thank you for feedback.
